server.port: 8888

# 数据库基本配置
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/sc_apsms?useUnicode=true&amp&characterEncoding=utf-8
  username: root
  password:
  driver-class-name: com.mysql.jdbc.Driver

spring.jpa.database: MYSQL
# 显示后台处理的SQL语句
spring.jpa.show-sql: true
# 自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表
#spring.jpa.hibernate.ddl-auto=: update
spring.jpa.properties.hibernate.hbm2ddl.auto: update

security.user.name: amber
security.user.password: 123
management.security.enabled: true
management.security.role: ADMIN


upload.img.url: /static/img/

logging.level.org.springframework.security: info

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800


#
##jsp
#spring:
#    # HTTP ENCODING
#    http:
#        encoding.charset: UTF-8
#        encoding.enable: true
#        encoding.force: true
#
#    datasource:
#        validation-query: SELECT 1
#        test-on-borrow: true
#
#    mvc:
#        view:
#            prefix: /static/imgs/
#            suffix: .jsp